language: python
sudo: false
os:
  - linux
python:
  - "3.4"
install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - >
    conda create -q -n test-environment
    python=$TRAVIS_PYTHON_VERSION
    coverage flake8 matplotlib nose numpy pandas pip scipy sympy tornado
  - source activate test-environment
  - pip install coveralls
  - pip install .
script:
  - coverage run --source mesa setup.py test

  # * E501 - line length limit
  # * E123 - indentation on data structures
  - flake8 . --ignore=F403,E501,E123,E128 --exclude=docs/
  - nosetests --with-coverage
after_success:
  - coveralls
