language: python
sudo: false
os:
  - linux
cache:
  pip: true
python:
  - "3.4"
  - "3.5"
  - "3.6"
  # - "nightly"
install:
  - pip install coveralls
  - pip install .[dev]
script:
  # * E501 - line length limit
  # * E123 - indentation on data structures
  - flake8 . --ignore=F403,E501,E123,E128 --exclude=docs,build
  - nosetests --with-coverage --cover-package=mesa
  # - ./tests/test_end_to_end_viz.sh  # needs to be investigated on why this took forever
after_success:
  - coveralls
