name: "Update Pipfile.lock"
on:
  schedule:
    - cron: '0 6 1 * *' # 1st day of each month at 06:00 UTC
  push:
    paths:
    - 'Pipfile'
    - '.github/workflows/update-pipfile.yml'

jobs:
  piplock:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - run: pip install -U pip
    - run: pip install -U wheel
    - run: pip install -U pipenv
    - run: pipenv lock
    - uses: actions/upload-artifact@v3
      with:
        name: "Pipfile lock"
        path: Pipfile.lock
    - uses: peter-evans/create-pull-request@v4
      with:
        title: "Update Pipfile.lock (dependencies)"
        branch: update-pipfile
        base: main
        commit-message: "[Bot] Update Pipfile.lock dependencies"
